apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusterdockerregistries.autoimagepullsecrets.io
spec:
  group: autoimagepullsecrets.io
  names:
    kind: ClusterDockerRegistry
    listKind: ClusterDockerRegistryList
    plural: clusterdockerregistries
    singular: clusterdockerregistry
  scope: Cluster
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: DockerRegistry is the Schema for the dockerregistries API
          type: object
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: DockerRegistrySpec defines the desired state of DockerRegistry
              type: object
              required:
                - authConfig
                - registry
              properties:
                authConfig:
                  description: Docker authentication configuration
                  type: object
                  properties:
                    identitytoken:
                      description: IdentityToken is used to authenticate the user and get an access token for the registry.
                      type: string
                      format: byte
                    password:
                      type: string
                      format: byte
                    registrytoken:
                      description: RegistryToken is a bearer token to be sent to a registry
                      type: string
                      format: byte
                    serveraddress:
                      type: string
                    username:
                      type: string
                      format: byte
                registry:
                  description: The docker registry that will be authenticated to
                  type: string
            status:
              description: DockerRegistryStatus defines the observed state of DockerRegistry
              type: object
      served: true
      storage: true
