{{- if .Values.certManager.enabled -}}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: "{{ .Release.Name }}-selfsigned-issuer"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: "{{ .Release.Name }}-{{ .Values.certSecret }}"
spec:
  dnsNames:
    - {{ include "autoimagepullsecrets-operator.fullname" . }}.{{ .Release.Namespace }}.svc
    - {{ include "autoimagepullsecrets-operator.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: "{{ .Release.Name }}-selfsigned-issuer"
  secretName: "{{ .Release.Name }}-{{ .Values.certSecret }}"
  {{- end -}}
