
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: '{{ .Release.Name }}-aips-operator'
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - autoimagepullsecrets.io
  resources:
  - clusterdockerregistries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoimagepullsecrets.io
  resources:
  - dockerregistries
  verbs:
  - get
  - list
  - watch
