apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aips-operator
  labels:
  {{- include "autoimagepullsecrets-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ .Release.Name }}-aips-operator'
subjects:
  - kind: ServiceAccount
    name: {{ include "autoimagepullsecrets-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
