apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ .Release.Name }}-aips-operator'
  labels:
    app: aips-operator
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    version: '{{ .Chart.AppVersion }}'
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - autoimagepullsecrets.io
    resources:
      - clusterdockerregistries
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - autoimagepullsecrets.io
    resources:
      - dockerregistries
    verbs:
      - get
      - list
      - watch
