apiVersion: v1
kind: Service
metadata:
  name: {{ include "autoimagepullsecrets-operator.fullname" . }}
  labels:
  {{- include "autoimagepullsecrets-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      protocol: TCP
      name: http-metrics
    - port: 9443
      protocol: TCP
      name: http-webhook
  selector:
  {{- include "autoimagepullsecrets-operator.selectorLabels" . | nindent 4 }}
