apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: '{{ include "autoimagepullsecrets-operator.fullname" . }}'
  labels:
    app: aips-operator
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    version: '{{ .Chart.AppVersion }}'
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/{{ .Values.certSecret }}'
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: '{{ include "autoimagepullsecrets-operator.fullname" . }}'
        namespace: '{{ .Release.Namespace }}'
    failurePolicy: Fail
    name: mpod.kb.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: '{{ include "autoimagepullsecrets-operator.fullname" . }}'
  labels:
    app: aips-operator
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    version: '{{ .Chart.AppVersion }}'
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/{{ .Values.certSecret }}'
webhooks:
  - clientConfig:
      caBundle: Cg==
      service:
        name: '{{ include "autoimagepullsecrets-operator.fullname" . }}'
        namespace: '{{ .Release.Namespace }}'
    failurePolicy: Fail
    matchPolicy: Equivalent
    name: mclusterdockerregistries.kb.io
    rules:
      - apiGroups:
          - autoimagepullsecrets.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - clusterdockerregistries
    sideEffects: None
  - clientConfig:
      caBundle: Cg==
      service:
        name: '{{ include "autoimagepullsecrets-operator.fullname" . }}'
        namespace: '{{ .Release.Namespace }}'
    failurePolicy: Fail
    name: mdockerregistries.kb.io
    rules:
      - apiGroups:
          - autoimagepullsecrets.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - dockerregistries
    sideEffects: None
