metadata:
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/serving-cert'
  labels:
    app: aips-operator
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
    version: '{{ .Chart.AppVersion }}'
spec:
  conversion:
    strategy: Webhook
    webhookClientConfig:
      caBundle: Cg==
      service:
        name: aips-operator-webhook-service
        namespace: system
        path: /convert
